enum AppLanguage { vi, en }

class AppStrings {
  AppStrings(this.language);

  final AppLanguage language;

  String t(String key) {
    return _dictionary[language]?[key] ?? key;
  }

  static const Map<AppLanguage, Map<String, String>> _dictionary = {
    AppLanguage.vi: {
      'app.title': 'IMISSHER Healthcare',
      'auth.title': 'Đăng nhập / Đăng ký',
      'auth.email': 'Email',
      'auth.password': 'Mật khẩu',
      'auth.fullName': 'Họ tên',
      'auth.login': 'Đăng nhập',
      'auth.register': 'Đăng ký',
      'auth.logout': 'Đăng xuất',
      'common.loading': 'Đang tải...',
      'common.error': 'Có lỗi xảy ra',
      'tabs.home': 'Trang chủ',
      'tabs.sos': 'SOS',
      'tabs.scanner': 'Quét',
      'tabs.medicines': 'Thuốc',
      'tabs.chatbot': 'Chatbot',
      'home.welcome': 'Chào mừng đến với IMISSHER',
      'home.medicalInfo': 'Thông tin y tế và liên hệ khẩn cấp',
      'home.openMedicalInfo': 'Mở thông tin y tế',
      'home.bloodType': 'Nhóm máu',
      'home.emergencyContact': 'Liên hệ khẩn cấp',
      'medical.title': 'Hồ sơ y tế',
      'medical.fullName': 'Họ tên',
      'medical.phone': 'Số điện thoại',
      'medical.bloodType': 'Nhóm máu',
      'medical.allergies': 'Dị ứng',
      'medical.chronicConditions': 'Bệnh nền',
      'medical.emergencyContactName': 'Tên người liên hệ khẩn cấp',
      'medical.emergencyContactPhone': 'SĐT liên hệ khẩn cấp',
      'medical.update': 'Cập nhật',
      'sos.title': 'Kích hoạt SOS',
      'sos.note': 'Ghi chú tình huống',
      'sos.send': 'Gửi SOS',
      'sos.success': 'Đã tạo sự cố SOS thành công',
      'scanner.title': 'Quét mã-vạch và khuôn-mặt',
      'scanner.desc': 'Nhập mã-vạch để tra cứu thuốc trong backend.',
      'scanner.barcodeLabel': 'Mã-vạch',
      'scanner.lookup': 'Tra cứu',
      'scanner.resultTitle': 'Kết quả tra cứu',
      'scanner.noResult': 'Không tìm thấy dữ liệu cho mã-vạch này.',
      'medicines.title': 'Danh sách thuốc',
      'medicines.refresh': 'Tải lại',
      'chatbot.title': 'Trợ lý y tế',
      'chatbot.message': 'Nhập câu hỏi',
      'chatbot.send': 'Gửi',
      'language.toggle': 'EN',
      'common.notProvided': 'Chưa cập nhật',
    },
    AppLanguage.en: {
      'app.title': 'IMISSHER Healthcare',
      'auth.title': 'Sign In / Register',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.fullName': 'Full name',
      'auth.login': 'Sign in',
      'auth.register': 'Register',
      'auth.logout': 'Sign out',
      'common.loading': 'Loading...',
      'common.error': 'Something went wrong',
      'tabs.home': 'Home',
      'tabs.sos': 'SOS',
      'tabs.scanner': 'Scanner',
      'tabs.medicines': 'Medicines',
      'tabs.chatbot': 'Chatbot',
      'home.welcome': 'Welcome to IMISSHER',
      'home.medicalInfo': 'Medical profile and emergency contacts',
      'home.openMedicalInfo': 'Open medical info',
      'home.bloodType': 'Blood type',
      'home.emergencyContact': 'Emergency contact',
      'medical.title': 'Medical profile',
      'medical.fullName': 'Full name',
      'medical.phone': 'Phone number',
      'medical.bloodType': 'Blood type',
      'medical.allergies': 'Allergies',
      'medical.chronicConditions': 'Chronic conditions',
      'medical.emergencyContactName': 'Emergency contact name',
      'medical.emergencyContactPhone': 'Emergency contact phone',
      'medical.update': 'Update',
      'sos.title': 'Trigger SOS',
      'sos.note': 'Situation note',
      'sos.send': 'Send SOS',
      'sos.success': 'SOS incident created successfully',
      'scanner.title': 'Barcode and face scanner',
      'scanner.desc':
          'Enter a barcode to query medicine metadata from backend.',
      'scanner.barcodeLabel': 'Barcode',
      'scanner.lookup': 'Lookup',
      'scanner.resultTitle': 'Lookup result',
      'scanner.noResult': 'No medicine metadata found for this barcode.',
      'medicines.title': 'Medicines',
      'medicines.refresh': 'Refresh',
      'chatbot.title': 'Medical assistant',
      'chatbot.message': 'Enter your question',
      'chatbot.send': 'Send',
      'language.toggle': 'VI',
      'common.notProvided': 'Not provided',
    },
  };
}
