enum AppLanguage { vi, en }

class AppStrings {
  AppStrings(this.language);

  final AppLanguage language;

  String t(String key) {
    return _dictionary[language]?[key] ?? key;
  }

  static const Map<AppLanguage, Map<String, String>> _dictionary = {
    AppLanguage.vi: {
      'app.title': 'Healthcare',
      'app.subtitle': 'Y tế thông minh cho tình huống khẩn cấp',
      'auth.title': 'Đăng nhập / Đăng ký',
      'auth.subtitle': 'Theo dõi thuốc, hồ sơ y tế và SOS trong một ứng dụng.',
      'auth.email': 'Email',
      'auth.emailHint': 'Nhập email',
      'auth.password': 'Mật khẩu',
      'auth.passwordHint': 'Nhập mật khẩu',
      'auth.fullName': 'Họ tên',
      'auth.fullNameHint': 'Nhập họ tên',
      'auth.login': 'Đăng nhập',
      'auth.register': 'Đăng ký',
      'auth.continue': 'Tiếp tục',
      'auth.sosHint': 'Bấm ngay để phát tín hiệu khẩn cấp',
      'auth.logout': 'Đăng xuất',
      'auth.switchToLogin': 'Đã có tài khoản? Đăng nhập',
      'auth.switchToRegister': 'Chưa có tài khoản? Đăng ký',
      'common.loading': 'Đang tải...',
      'common.error': 'Có lỗi xảy ra',
      'common.cancel': 'Hủy',
      'common.save': 'Lưu',
      'common.add': 'Thêm',
      'common.search': 'Tìm kiếm',
      'common.success': 'Thành công',
      'common.retry': 'Thử lại',
      'common.empty': 'Chưa có dữ liệu',
      'tabs.home': 'Trang chủ',
      'tabs.sos': 'SOS',
      'tabs.scanner': 'Quét',
      'tabs.medicines': 'Thuốc',
      'tabs.chatbot': 'Chatbot',
      'home.welcome': 'Chào mừng đến với Healthcare',
      'home.greeting': 'Chào bạn, hôm nay bạn thế nào...',
      'home.quickActions': 'Thao tác nhanh',
      'home.reminders': 'Lịch nhắc nhở',
      'home.createReminder': 'Tạo lời nhắc',
      'home.todaySchedule': 'Lịch hôm nay',
      'home.reminderComingSoon': 'Tính năng tạo lời nhắc sẽ sớm có mặt.',
      'home.defaultReminderMedicine': 'Uống thuốc - 08:00',
      'home.defaultReminderVaccine': 'Tiêm vaccine - 15:00',
      'home.medicalCardTitle': 'Hồ sơ y tế',
      'home.medicineCardTitle': 'Tủ thuốc',
      'home.medicalInfoCta': 'Mở hồ sơ y tế',
      'home.sosCta': 'Mở SOS',
      'home.medicalInfo': 'Thông tin y tế và liên hệ khẩn cấp',
      'home.openMedicalInfo': 'Mở thông tin y tế',
      'home.bloodType': 'Nhóm máu',
      'home.allergies': 'Dị ứng',
      'home.emergencyContact': 'Liên hệ khẩn cấp',
      'home.emergencyCount': 'Số liên hệ khẩn cấp',
      'medical.title': 'Hồ sơ y tế',
      'medical.fullName': 'Họ tên',
      'medical.phone': 'Số điện thoại',
      'medical.bloodType': 'Nhóm máu',
      'medical.allergies': 'Dị ứng',
      'medical.chronicConditions': 'Bệnh nền',
      'medical.emergencyContactName': 'Tên người liên hệ khẩn cấp',
      'medical.emergencyContactPhone': 'SĐT liên hệ khẩn cấp',
      'medical.emergencyContacts': 'Liên hệ khẩn cấp',
      'medical.addContact': 'Thêm liên hệ',
      'medical.removeContact': 'Xóa liên hệ',
      'medical.contactHint': 'Bạn có thể thêm tối đa 5 người liên hệ khẩn cấp.',
      'medical.contact': 'Liên hệ',
      'medical.requireName': 'Vui lòng nhập họ tên.',
      'medical.update': 'Cập nhật',
      'sos.title': 'Kích hoạt SOS',
      'sos.profileTitle': 'Hồ sơ người bệnh',
      'sos.personalInfo': 'Thông tin cá nhân',
      'sos.emergencyContacts': 'Liên hệ khẩn cấp',
      'sos.noContact': 'Chưa có liên hệ khẩn cấp.',
      'sos.callRelative': 'Gọi cho người thân',
      'sos.phoneCopied': 'Đã sao chép số điện thoại người thân.',
      'sos.subtitle': 'Gửi cảnh báo và ghi chú nhanh tới hệ thống SOS.',
      'sos.note': 'Ghi chú tình huống',
      'sos.send': 'Gửi SOS',
      'sos.success': 'Đã tạo sự cố SOS thành công',
      'sos.helper': 'Nhấn nút khi cần hỗ trợ khẩn cấp ngay lập tức.',
      'scanner.title': 'Quét mã vạch và khuôn mặt',
      'scanner.desc': 'Nhập mã vạch để tra cứu thông tin thuốc.',
      'scanner.barcodeLabel': 'Mã vạch',
      'scanner.lookup': 'Tra cứu',
      'scanner.resultTitle': 'Kết quả tra cứu',
      'scanner.noResult': 'Không tìm thấy dữ liệu cho mã-vạch này.',
      'medicines.title': 'Danh sách thuốc',
      'medicines.refresh': 'Tải lại',
      'medicines.empty': 'Chưa có thuốc nào để hiển thị.',
      'medicines.emptyMine': 'Bạn chưa có thuốc trong tủ thuốc cá nhân.',
      'medicines.searchHint': 'Tìm theo tên hoặc hoạt chất',
      'medicines.currentMedicines': 'Thuốc đang có',
      'medicines.totalTypes': 'Tổng số thuốc',
      'medicines.expired': 'Hết hạn',
      'medicines.nearExpiry': 'Sắp hết hạn',
      'medicines.quantity': 'Số lượng',
      'medicines.expiryDate': 'Hạn sử dụng',
      'medicines.reminderTime': 'Giờ nhắc',
      'medicines.defaultUnit': 'đơn vị',
      'medicines.unknown': 'Không rõ',
      'medicines.addDrug': 'Thêm thuốc mới',
      'medicines.addSuccess': 'Đã thêm thuốc mới thành công.',
      'medicines.formTitle': 'Thông tin thuốc mới',
      'medicines.formName': 'Tên thuốc',
      'medicines.formIngredient': 'Hoạt chất',
      'medicines.formQuantity': 'Số lượng',
      'medicines.formUnit': 'Đơn vị',
      'medicines.formBarcode': 'Mã vạch',
      'medicines.pickExpiryDate': 'Chọn hạn dùng',
      'medicines.pickReminderTime': 'Chọn giờ nhắc',
      'medicines.formDescription': 'Mô tả',
      'medicines.formContra': 'Chống chỉ định',
      'medicines.tagCustom': 'Tùy chỉnh',
      'medicines.tagCatalog': 'Thư viện',
      'chatbot.title': 'Trợ lý y tế',
      'chatbot.message': 'Nhập câu hỏi',
      'chatbot.send': 'Gửi',
      'chatbot.empty': 'Đặt câu hỏi để bắt đầu hội thoại với trợ lý y tế.',
      'chatbot.response': 'Trợ lý',
      'scanner.cameraMode': 'Chế độ máy ảnh',
      'scanner.qrMode': 'Quét mã QR',
      'scanner.barcodeMode': 'Quét mã vạch',
      'scanner.faceMode': 'Nhận diện khuôn mặt',
      'scanner.scanning': 'Đang quét...',
      'scanner.tapToScan': 'Hướng máy vào mã vạch để quét',
      'scanner.qrPrompt': 'Hướng máy vào mã QR để quét',
      'scanner.qrResultTitle': 'Kết quả mã QR',
      'scanner.qrUserId': 'Mã người dùng',
      'scanner.qrRaw': 'Nội dung thô',
      'scanner.faceHint': 'Chế độ nhận diện khuôn mặt đang được chuẩn bị. Vui lòng dùng luồng chụp ảnh chuyên dụng.',
      'scanner.switchMode': 'Đổi chế độ',
      'scanner.manualInput': 'Nhập thủ công',
      'sos.qrCode': 'Mã QR khẩn cấp',
      'sos.qrDesc': 'Người xung quanh quét mã này để xem thông tin y tế và gửi cảnh báo.',
      'sos.saveQr': 'Chia sẻ',
      'medicines.scanBarcode': 'Quét mã vạch',
      'medicines.manualInput': 'Nhập thủ công',
      'medicines.scanning': 'Đang quét mã vạch...',
      'medicines.scanResult': 'Kết quả quét',
      'medicines.fillQuantity': 'Vui lòng nhập số lượng.',
      'home.healthMetrics': 'Chỉ số sức khỏe',
      'home.noMetrics': 'Chưa có chỉ số nào.',
      'quickScan.title': 'Quét nhanh',
      'quickScan.desc': 'Quét mã QR hoặc mã vạch để xem thông tin.',
      'language.toggle': 'Tiếng Việt',
      'common.notProvided': 'Chưa cập nhật',
      'medicines.shellTitle': 'Tủ thuốc/Medicines shell',
      'errors.invalidCredentials': 'Email hoặc mật khẩu không chính xác',
      'errors.userNotFound': 'Tài khoản không tồn tại',
      'errors.emailExists': 'Email đã được đăng ký',
      'errors.unauthorized': 'Bạn không được phép truy cập',
      'errors.serverError': 'Lỗi máy chủ, vui lòng thử lại',
      'errors.networkError': 'Lỗi kết nối, vui lòng kiểm tra internet',
    },
    AppLanguage.en: {
      'app.title': 'Healthcare',
      'app.subtitle': 'Smart care for emergency moments',
      'auth.title': 'Sign In / Register',
      'auth.subtitle': 'Manage medicines, medical profile, and SOS in one app.',
      'auth.email': 'Email',
      'auth.emailHint': 'Enter email',
      'auth.password': 'Password',
      'auth.passwordHint': 'Enter password',
      'auth.fullName': 'Full name',
      'auth.fullNameHint': 'Enter full name',
      'auth.login': 'Sign in',
      'auth.register': 'Register',
      'auth.continue': 'Continue',
      'auth.sosHint': 'Tap now to send an emergency signal',
      'auth.logout': 'Sign out',
      'auth.switchToLogin': 'Already have an account? Sign in',
      'auth.switchToRegister': "Don't have an account? Register",
      'common.loading': 'Loading...',
      'common.error': 'Something went wrong',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'common.add': 'Add',
      'common.search': 'Search',
      'common.success': 'Success',
      'common.retry': 'Retry',
      'common.empty': 'No data yet',
      'tabs.home': 'Home',
      'tabs.sos': 'SOS',
      'tabs.scanner': 'Scanner',
      'tabs.medicines': 'Medicines',
      'tabs.chatbot': 'Chatbot',
      'home.welcome': 'Welcome to Healthcare',
      'home.greeting': 'Hi, how are you feeling today...',
      'home.quickActions': 'Quick actions',
      'home.reminders': 'Reminders',
      'home.createReminder': 'Create reminder',
      'home.todaySchedule': 'Today schedule',
      'home.reminderComingSoon': 'Reminder creation is coming soon.',
      'home.defaultReminderMedicine': 'Take medicine - 08:00',
      'home.defaultReminderVaccine': 'Vaccination - 15:00',
      'home.medicalCardTitle': 'Medical profile',
      'home.medicineCardTitle': 'Medicine cabinet',
      'home.medicalInfoCta': 'Open medical profile',
      'home.sosCta': 'Open SOS',
      'home.medicalInfo': 'Medical profile and emergency contacts',
      'home.openMedicalInfo': 'Open medical info',
      'home.bloodType': 'Blood type',
      'home.allergies': 'Allergies',
      'home.emergencyContact': 'Emergency contact',
      'home.emergencyCount': 'Emergency contacts',
      'medical.title': 'Medical profile',
      'medical.fullName': 'Full name',
      'medical.phone': 'Phone number',
      'medical.bloodType': 'Blood type',
      'medical.allergies': 'Allergies',
      'medical.chronicConditions': 'Chronic conditions',
      'medical.emergencyContactName': 'Emergency contact name',
      'medical.emergencyContactPhone': 'Emergency contact phone',
      'medical.emergencyContacts': 'Emergency contacts',
      'medical.addContact': 'Add contact',
      'medical.removeContact': 'Remove contact',
      'medical.contactHint': 'You can add up to 5 emergency contacts.',
      'medical.contact': 'Contact',
      'medical.requireName': 'Please enter full name.',
      'medical.update': 'Update',
      'sos.title': 'Trigger SOS',
      'sos.profileTitle': 'Patient profile',
      'sos.personalInfo': 'Personal information',
      'sos.emergencyContacts': 'Emergency contacts',
      'sos.noContact': 'No emergency contact yet.',
      'sos.callRelative': 'Call relative',
      'sos.phoneCopied': 'Relative phone number copied.',
      'sos.subtitle': 'Send a quick alert and notes to the SOS system.',
      'sos.note': 'Situation note',
      'sos.send': 'Send SOS',
      'sos.success': 'SOS incident created successfully',
      'sos.helper': 'Tap the button when immediate support is needed.',
      'scanner.title': 'Barcode and face scanner',
      'scanner.desc':
          'Enter a barcode to query medicine metadata from backend.',
      'scanner.barcodeLabel': 'Barcode',
      'scanner.lookup': 'Lookup',
      'scanner.resultTitle': 'Lookup result',
      'scanner.noResult': 'No medicine metadata found for this barcode.',
      'medicines.title': 'Medicines',
      'medicines.refresh': 'Refresh',
      'medicines.empty': 'No medicines to display.',
      'medicines.emptyMine': 'No medicine in your cabinet yet.',
      'medicines.searchHint': 'Search by name or ingredient',
      'medicines.currentMedicines': 'Current medicines',
      'medicines.totalTypes': 'Total medicines',
      'medicines.expired': 'Expired',
      'medicines.nearExpiry': 'Near expiry',
      'medicines.quantity': 'Quantity',
      'medicines.expiryDate': 'Expiry date',
      'medicines.reminderTime': 'Reminder time',
      'medicines.defaultUnit': 'unit',
      'medicines.unknown': 'Unknown',
      'medicines.addDrug': 'Add new medicine',
      'medicines.addSuccess': 'Medicine added successfully.',
      'medicines.formTitle': 'New medicine details',
      'medicines.formName': 'Medicine name',
      'medicines.formIngredient': 'Active ingredient',
      'medicines.formQuantity': 'Quantity',
      'medicines.formUnit': 'Unit',
      'medicines.formBarcode': 'Barcode',
      'medicines.pickExpiryDate': 'Pick expiry date',
      'medicines.pickReminderTime': 'Pick reminder time',
      'medicines.formDescription': 'Description',
      'medicines.formContra': 'Contraindications',
      'medicines.tagCustom': 'Custom',
      'medicines.tagCatalog': 'Catalog',
      'chatbot.title': 'Medical assistant',
      'chatbot.message': 'Enter your question',
      'chatbot.send': 'Send',
      'chatbot.empty': 'Ask a question to start chatting with the assistant.',
      'chatbot.response': 'Assistant',
      'scanner.cameraMode': 'Camera mode',
      'scanner.qrMode': 'QR scan',
      'scanner.barcodeMode': 'Barcode scan',
      'scanner.faceMode': 'Face recognition',
      'scanner.scanning': 'Scanning...',
      'scanner.tapToScan': 'Point the camera at a barcode to scan',
      'scanner.qrPrompt': 'Point the camera at a QR code to scan',
      'scanner.qrResultTitle': 'QR result',
      'scanner.qrUserId': 'User ID',
      'scanner.qrRaw': 'Raw content',
      'scanner.faceHint': 'Face recognition is handled through the dedicated capture flow.',
      'scanner.switchMode': 'Switch mode',
      'scanner.manualInput': 'Manual input',
      'sos.qrCode': 'Emergency QR Code',
      'sos.qrDesc': 'Bystanders scan this code to view medical info and send an alert.',
      'sos.saveQr': 'Share',
      'medicines.scanBarcode': 'Scan barcode',
      'medicines.manualInput': 'Manual input',
      'medicines.scanning': 'Scanning barcode...',
      'medicines.scanResult': 'Scan result',
      'medicines.fillQuantity': 'Please enter quantity.',
      'home.healthMetrics': 'Health metrics',
      'home.noMetrics': 'No metrics yet.',
      'quickScan.title': 'Quick Scan',
      'quickScan.desc': 'Scan a QR code or barcode to view info.',
      'language.toggle': 'English',
      'common.notProvided': 'Not provided',
      'medicines.shellTitle': 'Medicine Cabinet/Medicines shell',
      'errors.invalidCredentials': 'Invalid email or password',
      'errors.userNotFound': 'Account does not exist',
      'errors.emailExists': 'Email already registered',
      'errors.unauthorized': 'You are not authorized to access this',
      'errors.serverError': 'Server error, please try again',
      'errors.networkError': 'Network error, please check your connection',
    },
  };
}
